// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGa2vhWYS89KAdVQy46p2QYI4rpYrYfn4',
    appId: '1:183102386408:web:77f9d7954ba360363d595d',
    messagingSenderId: '183102386408',
    projectId: 'otista-gym-b85ab',
    authDomain: 'otista-gym-b85ab.firebaseapp.com',
    storageBucket: 'otista-gym-b85ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeMkC2N8fryCAxiVhs2E6RufJ3FUXdAuU',
    appId: '1:183102386408:android:63934f1380f2a3f53d595d',
    messagingSenderId: '183102386408',
    projectId: 'otista-gym-b85ab',
    storageBucket: 'otista-gym-b85ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mqp0yHrUv54CfoiHexUerpel4k8YbuU',
    appId: '1:183102386408:ios:c2fd2c60811810093d595d',
    messagingSenderId: '183102386408',
    projectId: 'otista-gym-b85ab',
    storageBucket: 'otista-gym-b85ab.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiManajemenGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mqp0yHrUv54CfoiHexUerpel4k8YbuU',
    appId: '1:183102386408:ios:c2fd2c60811810093d595d',
    messagingSenderId: '183102386408',
    projectId: 'otista-gym-b85ab',
    storageBucket: 'otista-gym-b85ab.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiManajemenGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGa2vhWYS89KAdVQy46p2QYI4rpYrYfn4',
    appId: '1:183102386408:web:ae2b690d3dd755883d595d',
    messagingSenderId: '183102386408',
    projectId: 'otista-gym-b85ab',
    authDomain: 'otista-gym-b85ab.firebaseapp.com',
    storageBucket: 'otista-gym-b85ab.firebasestorage.app',
  );
}
